version: "3.9"

services:
  db:
    image: redis:alpine
    hostname: redis
    ports:
      - "6379:6379"
  app:
    image: app
    deploy:
      mode: replicated
      replicas: 3
    ports:
      - "80:8080"

#  local_storage:
#    image: mcr.microsoft.com/azure-blob-storage
#    ports:
#      - 10000:10000
#      - 10001:10001
#  local_functions:
#    image: mcr.microsoft.com/azure-functions/java:4-java8
#    hostname: afunctions
#    ports:
#      - 8080:80
#    depends_on:
#      - local.storage.emulator